### ISSUE TITLE
Invalid image value

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-operator#545] opened 2020-03-03 02:48 UTC
my kabanero-index has the following:
```
apiVersion: v2
stacks:
- id: java-microprofile
  name: Eclipse MicroProfile®
  version: 0.2.25
  description: Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
  license: Apache-2.0
  language: java
  maintainers:
  - name: Emily Jiang
    email: emijiang6@googlemail.com
    github-id: Emily-Jiang
  - name: Neeraj Laad
    email: neeraj.laad@gmail.com
    github-id: neeraj-laad
  - name: Ozzy
    email: ozzy@ca.ibm.com
    github-id: BarDweller
  default-template: default
  src: http://kabanero-index-kabanero.apps.lisa7.gawor.me/java-microprofile.v0.2.25.source.tar.gz
  templates:
  - id: default
    url: http://kabanero-index-kabanero.apps.lisa7.gawor.me/java-microprofile.v0.2.25.templates.default.tar.gz
  requirements:
    appsody-version: '>= 0.5.0'
  image: image-registry.openshift-image-registry.svc:5000/kabanero/java-microprofile:0.2.25
```
The CR is configured to point at this index. The operator created the following stack for it:

```
$ oc get stack java-microprofile -o yaml
apiVersion: kabanero.io/v1alpha2
kind: Stack
metadata:
  creationTimestamp: "2020-03-03T02:41:46Z"
  finalizers:
  - kabanero.io/stack-controller
  generation: 1
  name: java-microprofile
  namespace: kabanero
  ownerReferences:
  - apiVersion: kabanero.io/v1alpha2
    controller: true
    kind: Kabanero
    name: kabanero
    uid: 2cd39aa8-b4d1-4537-99f1-c17405904d9f
  resourceVersion: "1214352"
  selfLink: /apis/kabanero.io/v1alpha2/namespaces/kabanero/stacks/java-microprofile
  uid: 0530a0ab-6d02-477f-8ee2-55ca88828271
spec:
  name: java-microprofile
  versions:
  - images:
    - id: Eclipse MicroProfile®
      image: image-registry.openshift-image-registry.svc
    pipelines:
    - https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.0/default-kabanero-pipelines.tar.gz
      id: default
      sha256: abbc2ed0e19349aa5e23b511b75449fb1a515cfd6a548b05b6516fb7c6de1aba
    version: 0.2.25
status:
  versions:
  - images:
    - id: Eclipse MicroProfile®
      image: image-registry.openshift-image-registry.svc
    pipelines:
    - activeAssets:
      ...
      digest: abbc2ed0e19349aa5e23b511b75449fb1a515cfd6a548b05b6516fb7c6de1aba
      name: default
      url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.0/default-kabanero-pipelines.tar.gz
    status: active
    version: 0.2.25
```

Notice the `image` values in the Stack CR vs kabanero-index.yaml. Everything after the first `:` got dropped in the Stack CR. This causes stack validation to fail in a pipeline.

**Comment by jgawor** [comment] 2020-03-03 03:10
Problem might be in https://github.com/kabanero-io/kabanero-operator/blob/master/pkg/controller/stack/utils/stacks.go#L29

**Comment by marikaj123** [comment] 2020-03-03 21:58
@jgawor - Please verify and close the issue. Thank you.

**Comment by kaczyns** [comment] 2020-03-04 17:16
@jgawor release 0.6.1-rc.1 is available for you to verify with, when you are ready.

**Comment by jgawor** [comment] 2020-03-06 05:45
With the latest fix from rc.2 I see the following error:
```
{"level":"error","ts":1583472686.6945498,"logger":"controller_kabaneroplatform","msg":"Error reconciling featured stacks.","Request.Namespace":"kabanero","Request.Name":"kabanero","error":"admission webhook \"validating.stack.kabanero.io\" denied the request: Image image-registry.openshift-image-registry.svc:5000/kabanero/nodejs-express associated with Stack nodejs-express 0.2.10 should not contain an image tag. Stack: &{{Stack kabanero.io/v1alpha2} {nodejs-express  kabanero  8e775742-092d-4010-bcdf-b83c44b5c043  1 2020-03-06 05:31:26 +0000 UTC <nil> <nil> map[] map[] [{kabanero.io/v1alpha2 Kabanero kabanero ba188750-a56e-47a9-951e-dd363f69586a 0xc000798248 <nil>}] nil []  []} {nodejs-express [{[{default abbc2ed0e19349aa5e23b511b75449fb1a515cfd6a548b05b6516fb7c6de1aba {https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.0/default-kabanero-pipelines.tar.gz false}}] 0.2.10  false [{Node.js Express image-registry.openshift-image-registry.svc:5000/kabanero/nodejs-express}]}]} { []}}","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform.(*ReconcileKabanero).Reconcile\n\tsrc/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/kabaneroplatform_controller.go:317\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88"}
```

I guess the problem is now in: https://github.com/kabanero-io/kabanero-operator/blob/master/pkg/webhook/stack/validatingwebhook.go#L96

**Comment by kaczyns** [comment] 2020-03-06 17:57
kabanero-operator 0.6.1-rc.3 is available and contains the latest fix for this issue.  Here is a summary of what the problem is and what has been fixed so far:

Problem: colons in the hostname portion of the stack container image path are being treated as the tag separator when Kabanero strips off the tag from a stack container image.

Iteration 1 - tried to strip characters to the right of the last colon found in the container image path.  However if the transformation is applied again, it will now find the colon in the hostname and strip that next time.  Since the transform occurs in the mutating webhook, it can be applied multiple times (on create, and then later again on update).

Iteration 2 - if the last colon found contains a forward slash character to its right, ignore it.  The only two places where it is valid to have a colon in the container image path are the first path component (the hostname) and the tag separator.  Since the first path component must be followed by a second path component, separated by a forward slash, we can ignore any colon found before a slash.

Iteration 3 - The stack validating webhook contained a check for colons in the container image path, and rejects the stack object if a colon is found.  The validating webhook needed to change to allow the colon in the first path component of the container image path.  This was accomplished in the code by trying to remove the image tag again.  The resulting string should match the input string exactly (if it removed the tag, then a tag was present and we reject the object).

We now have several unit tests which use "internal" image registry path names (with the hostname:port format) across the kabanero controller, mutating webhook and validating webhook.  We can verify during a build that the individual components are handling the container image path correctly, but we still lack an end-to-end test.

**Comment by marikaj123** [comment] 2020-03-09 13:33
According to @jgawor the issue was verified and can be closed.

**Closed by marikaj123** 2020-03-09 13:33 UTC
Labels: bug, stop-ship
