### ISSUE TITLE
Update go.sum for operator-sdk v0.11

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#409] opened 2020-01-22 19:41 UTC
Seems to be mismatched

**Comment by kaczyns** [comment] 2020-02-06 19:08
In PR #410 we discovered that the mismatch is caused by compiling with go 1.12.x vs 1.13.x.  Lets turn this into a "move to go 1.13.x" issue, and upgrade to operator-sdk v0.12.0 which also requires go 1.13.x.  

The operator-sdk upgrade guide has some information about moving to v0.12.0, and it looks pretty simple:
https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md

You can also use `operator-sdk print-deps` to see what the updated `go.mod` should contain (the relevant bits go at the bottom of `go.mod`).

**Comment by kaczyns** [comment] 2020-02-06 19:11
FWIW if you want to come up further than v0.12.0, that's fine.... the upgrade guide doesn't have any information for those releases, but the releases page lists the breaking changes.  It looks like we should stop using `operator-sdk generate openapi` in v0.13.0.  I don't think we use those generated files anyway.

**Comment by kaczyns** [comment] 2020-02-18 20:54
Fixed in #460

**Closed by kaczyns** 2020-02-18 20:54 UTC
