### ISSUE TITLE
Allow the same pipeline name to be used for more than one Appsody Collection.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-operator#114] opened 2019-08-21 12:06 UTC
A current limitation of the Kabanero operator requires that collection pipelines be uniquely named.  This limitation makes managing the collection pipelines difficult when the same pipeline could (and should) be used to support multiple collections.

**Comment by stephenkinder** [comment] 2019-08-21 13:39
@kaczyns pointed out that in addition to the Pipeline artifacts in the collection, there are other resources in the collection that might also be sources of conflict.  Ideally, we need to articulate each artifact in the collections and have an approach for disambiguating reuse where appropriate.

**Comment by kyleschlosser** [comment] 2019-08-29 17:32
@stephenkinder @smcclem I am working on a solution which allows you to incorporate directives into the yaml. This prevents us from needing a new requirement on the collection format. 

**Here is an example:** 
```
#Kabanero! on activate substitute CollectionName for text '${collection-name}'
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ${collection-name}-build-deploy-pipeline
spec:
  resources:
  - resource1
  tasks:
    - name: build-task
      taskRef:
        name: ${collection-name}-build-task
```

The directive `#Kabanero! on activate substitute CollectionName for text '${collection-name}'` tells the rendering engine to replace the text '${collection-name}' with the name of the collection at activation time. 

Currently, only text substitution is allowed, and CollectionName is the only recognized replacement.

**Comment by kyleschlosser** [comment] 2019-08-30 19:30
The code for this is about complete, we are doing final reviews. However, I think taking in an enhancement like this now is probably taking on too much risk given that we want to do a release build in our next business day.

**Comment by kyleschlosser** [comment] 2019-09-03 17:46
This code has been merged

**Comment by tseelbach** [comment] 2019-09-06 15:17
Seems that the operator is using a descriptive name rather than the name token without spaces

It should use the id field rather than the name field

**Comment by kaczyns** [comment] 2019-09-06 15:24
The issue is as Tom says, the name field can contain Unicode characters (such as the copyright symbol) which don't represent well in object names.  The id field is currently not using Unicode characters, although I can't see anything that would prevent a Unicode character from being used there.  We'll try to switch to using the id field instead.

**Comment by kyleschlosser** [comment] 2019-09-06 19:36
The function provided in the original pull request has now been enhanced to work for both collection name and collection id substitution.

**Closed by kyleschlosser** 2019-09-06 19:36 UTC
Labels: release-0.1, status-Green
