### ISSUE TITLE
Edge termination for landing page

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-operator#178] opened 2019-09-10 06:09 UTC
Use edge TLS termination for the landing page instead of using certificates generated by the landing container. This way, on certain environments (e.g. IBM Cloud) the edge certificate is already trusted by the browsers.

**Comment by kaczyns** [comment] 2019-09-20 20:00
@jgawor I am reading thru the edge termination policy.
https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#secured-routes
The route can optionally specify a certificate to use.  I am guessing based on your initial comment that you want us to skip this, and just have the route use the router's default certificate?  Or were you thinking that the install process would somehow generate a unique certificate for the route and use that instead?

@jtmulvey I need your input here on using edge vs re-encryption termination.
https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#secured-routes
For an edge route, SSL is terminated at the router, and then traffic between the router and the back-end (pod) is unsecured.  re-encryption allows the traffic between the router and the back-end (pod) to also be secured, using the certificate provided by the back-end (pod).  Most of the time this certificate is an un-trusted self-signed certificate provided by Liberty.  It's not clear to me how to tell the router that it can trust this self-signed certificate without extracting it and adding it to the route configuration, which isn't possible today.

**Comment by kaczyns** [comment] 2019-12-16 20:33
This is going to have multiple parts to get to where we need to be.  Rather than have OpenShift trust the self-signed cert that Liberty uses, we're going to have Liberty use a certificate generated by OpenShift.
1) Configure OpenShift to generate a certificate into the landing page pod.  See https://docs.openshift.com/container-platform/4.2/authentication/certificates/service-serving-certificate.html.  For an example of how we did this with kabanero-eventing, see https://github.com/kabanero-io/kabanero-operator/blob/master/config/orchestrations/events/0.1/kabanero-events.yaml.
2) Convert the certificate to a keystore.  See https://developers.redhat.com/blog/2017/11/22/dynamically-creating-java-keystores-openshift/.  The certificate from step 1 should be mounted in the file system and we should use the `keytool` command to create a keystore from it.  We will need to consider what container should build the keystore.  We could use an init container as the example does, or do it right in the main container before we start Liberty.  If we do it in the init container we must choose carefully what image we use, or build our own.  The UBI base image (but not UBI-min) has openSSL, and the landing page image should have keytool I think but someone would need to verify that.
3) Update the liberty configuration for the landing page to use the keystore that was built in step 2.  This probably ends up being the easiest part :-)

**Comment by jgawor** [comment] 2019-12-16 20:52
For 2), you don't need to convert to a keystore. you just need to convert into pkcs12 file which Liberty understands natively (and of course, point Liberty to it or put in the right place). also, you can use the landing image as for the init container purposes :)

**Comment by jtmulvey** [comment] 2019-12-17 15:15
@kaczyns @jgawor We are working on an item to enable the OpenShift Cert Manager in Kabanero and make it available to the Open Liberty operator now.  Ut Le and @arkarkala  are now working on this. We should probably discuss this and coordinate.  Ut found he had to install the Cert Manager and configure it as part of this. We expected this should be done by the Kab operator.

**Comment by jtmulvey** [comment] 2019-12-17 15:16
See : https://github.com/kabanero-io/kabanero-security/issues/49
and
https://github.com/kabanero-io/kabanero-security/issues/48

**Comment by kaczyns** [comment] 2019-12-17 15:50
@jtmulvey Ut and I spoke about this a couple of weeks ago, we understand that a broader solution is coming.

**Comment by mezarin** [comment] 2020-01-09 15:24
The Kabanero implementation for this is complete, but it is being set aside for now because the Liberty image currently being used by the landing page does not have the openssl installed. The openssl command should have been installed, but there is an issue with the image being used. The issue was reported here:   https://github.com/AdoptOpenJDK/openjdk-docker/issues/256.

A workaround would be for the landing page to temporarily install the openssl command until issue 256 is resolved, but it was decided that it would be best to wait.
(UBI based images do not have openssl installed) 

Here is the implementation: https://github.com/mezarin/kabanero-operator/commit/3b4f6920b756b0cea053e6da9ea0db6f94cf0ece. This code does not use the broader certificate manager support Jim mentioned as it is not available. It also uses reencypt termination and opposed to edge termination to encrypt the entire client/server path.

If/When this update is merged, here is the required landing page update:

src/main/wlp/server.xml: 

```
    <keyStore id="kabaneroLanding" 
              password="changeit"
              location="/etc/tls/secrets/java.io/landingpage/keystores/keystore.p12"
              type="PKCS12"/>
    <ssl id="defaultSSLConfig" keyStoreRef="kabaneroLanding" trustDefaultCerts="true" sslProtocol="TLSv1.2"/>
```
If the above server.xml update is not made, the following exception is generated as expected when trying to access the landing page:

```[1/8/20 16:20:51:801 UTC] 00000085 com.ibm.ws.channel.ssl.internal.SSLHandshakeErrorTracker     E CWWKO0801E: Unable to initialize SSL connection. Unauthorized access was denied or security settings have expired. Exception is javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1781)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1070)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:896)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:766)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at com.ibm.ws.channel.ssl.internal.SSLUtils.handleHandshake(SSLUtils.java:900)
...```

**Comment by kaczyns** [comment] 2020-02-18 20:56
It looks like AdoptOpenJDK/openjdk-docker#256 has closed.  However if that does not work out, there is a `kabanero-utils` container which we can add `openssl` to, and use as the init container.  The `kabanero-utils` container is currently used by the kabanero pipelines.

**Comment by mezarin** [comment] 2020-03-25 20:25
I am picking this up again given what Tim mentioned.

**Comment by dacleyra** [comment] 2020-03-27 19:30
Liberty container has a built in helper for converting certs to a store.
https://github.com/WASdev/ci.docker/blob/master/ga/20.0.0.3/kernel/helpers/runtime/docker-server.sh

**Comment by jtmulvey** [comment] 2020-03-28 14:44
@mezarin @jarek is correct. Artur just added this support as part of the cert manager support for the cluster that Ut Le developed.  It was intended to be generic enough that it could be used by cert manager or any other similar implementation. The cert manager for Kabanero is provided as a sample today. We continue to discuss a more general OpenShift Cert Manager impl with Red Hat.

**Comment by kaczyns** [comment] 2020-04-07 14:27
There is still a bit of work to do, to edit version.yaml when the landing page bits are merged.

**Comment by kaczyns** [comment] 2020-04-16 19:52
ok this is finished now, I'm closing.

**Closed by kaczyns** 2020-04-16 19:52 UTC
